export type FlavorRegion = "NorCal" | "SoCal"

export interface IceCreamFlavor {
  id: number
  name: string
  shop: string
  shopSlug: string
  city: string
  region: FlavorRegion
  price: string
  description: string
  vibes: string[]
  featured: boolean
}

export const FLAVORS: IceCreamFlavor[] = [
  // ── BI-RITE CREAMERY · San Francisco ──────────────────────────
  {
    id: 1,
    name: "Salted Caramel",
    shop: "Bi-Rite Creamery",
    shopSlug: "bi-rite-creamery",
    city: "San Francisco",
    region: "NorCal",
    price: "$5.50",
    description: "The scoop that started the artisan caramel revolution. Deep, buttery, with just enough salt to keep you going back.",
    vibes: ["nutty", "unique"],
    featured: true,
  },
  {
    id: 2,
    name: "Ricanelas",
    shop: "Bi-Rite Creamery",
    shopSlug: "bi-rite-creamery",
    city: "San Francisco",
    region: "NorCal",
    price: "$5.50",
    description: "Cinnamon horchata ice cream — the Mission District in a single scoop. Warm spice, cold cream.",
    vibes: ["unique", "savory-sweet"],
    featured: false,
  },
  {
    id: 3,
    name: "Balsamic Strawberry",
    shop: "Bi-Rite Creamery",
    shopSlug: "bi-rite-creamery",
    city: "San Francisco",
    region: "NorCal",
    price: "$5.50",
    description: "Seasonal Swanton Farm strawberries with aged balsamic. Proof that ice cream can be genuinely sophisticated.",
    vibes: ["fruity"],
    featured: false,
  },
  // ── HUMPHRY SLOCOMBE · San Francisco ─────────────────────────
  {
    id: 4,
    name: "Secret Breakfast",
    shop: "Humphry Slocombe",
    shopSlug: "humphry-slocombe",
    city: "San Francisco",
    region: "NorCal",
    price: "$6.00",
    description: "Bourbon ice cream loaded with cornflake cookies. The most-Instagrammed scoop in SF for a reason.",
    vibes: ["nutty", "unique"],
    featured: true,
  },
  {
    id: 5,
    name: "Blue Bottle Vietnamese Coffee",
    shop: "Humphry Slocombe",
    shopSlug: "humphry-slocombe",
    city: "San Francisco",
    region: "NorCal",
    price: "$6.00",
    description: "Cold brew intensity from Blue Bottle Coffee, churned into a dense, café-perfect scoop.",
    vibes: ["unique"],
    featured: false,
  },
  {
    id: 6,
    name: "Brown Butter Bourbon",
    shop: "Humphry Slocombe",
    shopSlug: "humphry-slocombe",
    city: "San Francisco",
    region: "NorCal",
    price: "$6.00",
    description: "Toasted nuttiness of brown butter meets the slow heat of bourbon. Grown-up ice cream at its best.",
    vibes: ["nutty"],
    featured: false,
  },
  // ── SMITTEN ICE CREAM · San Francisco ────────────────────────
  {
    id: 7,
    name: "Tahitian Vanilla Bean",
    shop: "Smitten Ice Cream",
    shopSlug: "smitten-ice-cream",
    city: "San Francisco",
    region: "NorCal",
    price: "$6.50",
    description: "Made to order with liquid nitrogen. The most honest vanilla you'll ever eat — floral, rich, impossibly fresh.",
    vibes: ["unique"],
    featured: false,
  },
  {
    id: 8,
    name: "Bourbon Brown Butter",
    shop: "Smitten Ice Cream",
    shopSlug: "smitten-ice-cream",
    city: "San Francisco",
    region: "NorCal",
    price: "$7.00",
    description: "Nitrogen-spun on the spot. Silkier than any scoop made hours earlier — this is what the technology is for.",
    vibes: ["nutty", "unique"],
    featured: false,
  },
  {
    id: 9,
    name: "Strawberry Balsamic",
    shop: "Smitten Ice Cream",
    shopSlug: "smitten-ice-cream",
    city: "San Francisco",
    region: "NorCal",
    price: "$6.50",
    description: "Peak-season California strawberries, spun fresh in liquid nitrogen with a balsamic swirl.",
    vibes: ["fruity"],
    featured: false,
  },
  // ── FENTONS CREAMERY · Oakland ────────────────────────────────
  {
    id: 10,
    name: "Black & Tan Sundae",
    shop: "Fentons Creamery",
    shopSlug: "fentons-creamery",
    city: "Oakland",
    region: "NorCal",
    price: "$9.50",
    description: "Vanilla and chocolate ice cream, toasted almond, hot fudge, whipped cream. The sundae Pixar made famous — and it earns every frame.",
    vibes: ["chocolate", "nutty"],
    featured: true,
  },
  {
    id: 11,
    name: "Toasted Almond",
    shop: "Fentons Creamery",
    shopSlug: "fentons-creamery",
    city: "Oakland",
    region: "NorCal",
    price: "$6.00",
    description: "A Fentons signature since 1894. Roasted California almonds folded into a cream base that tastes like it hasn't changed in a century — because it hasn't.",
    vibes: ["nutty"],
    featured: false,
  },
  {
    id: 12,
    name: "Butterscotch",
    shop: "Fentons Creamery",
    shopSlug: "fentons-creamery",
    city: "Oakland",
    region: "NorCal",
    price: "$6.00",
    description: "Old-school butterscotch from a 130-year-old recipe. Rich, caramelized, deeply nostalgic.",
    vibes: ["nutty"],
    featured: false,
  },
  // ── TUCKER'S ICE CREAM · Oakland ─────────────────────────────
  {
    id: 13,
    name: "Tin Roof Sundae",
    shop: "Tucker's Ice Cream",
    shopSlug: "tuckers-ice-cream",
    city: "Oakland",
    region: "NorCal",
    price: "$5.50",
    description: "Vanilla ice cream, chocolate fudge, and salted peanuts — Tucker's has been making this since 1940 and it still hits.",
    vibes: ["nutty", "chocolate"],
    featured: false,
  },
  {
    id: 14,
    name: "Old School Chocolate Fudge",
    shop: "Tucker's Ice Cream",
    shopSlug: "tuckers-ice-cream",
    city: "Oakland",
    region: "NorCal",
    price: "$5.00",
    description: "Dense, serious chocolate from one of Oakland's oldest neighborhood creameries. No gimmicks.",
    vibes: ["chocolate"],
    featured: false,
  },
  // ── PENNY ICE CREAMERY · Santa Cruz ──────────────────────────
  {
    id: 15,
    name: "Lavender Honey",
    shop: "Penny Ice Creamery",
    shopSlug: "penny-ice-creamery",
    city: "Santa Cruz",
    region: "NorCal",
    price: "$5.50",
    description: "Local Santa Cruz honey, culinary-grade lavender. Floral without being soap. Seasonal without being precious.",
    vibes: ["floral"],
    featured: true,
  },
  {
    id: 16,
    name: "Burnt Caramel",
    shop: "Penny Ice Creamery",
    shopSlug: "penny-ice-creamery",
    city: "Santa Cruz",
    region: "NorCal",
    price: "$5.50",
    description: "Caramel taken right to the edge before it becomes bitter. Penny's best single-flavor achievement.",
    vibes: ["nutty"],
    featured: false,
  },
  {
    id: 17,
    name: "Cardamom Rose",
    shop: "Penny Ice Creamery",
    shopSlug: "penny-ice-creamery",
    city: "Santa Cruz",
    region: "NorCal",
    price: "$5.50",
    description: "Persian-inspired spice meets California dairy. Seasonal, rotating, worth calling ahead to confirm.",
    vibes: ["floral", "unique"],
    featured: false,
  },
  // ── MARIANNE'S ICE CREAM · Santa Cruz ────────────────────────
  {
    id: 18,
    name: "Classic Vanilla Bean",
    shop: "Marianne's Ice Cream",
    shopSlug: "marianne-ice-cream",
    city: "Santa Cruz",
    region: "NorCal",
    price: "$4.50",
    description: "Made from the same recipe since 1947. Santa Cruz's oldest creamery proves simplicity wins when the ingredients are right.",
    vibes: ["unique"],
    featured: false,
  },
  {
    id: 19,
    name: "Banana Split",
    shop: "Marianne's Ice Cream",
    shopSlug: "marianne-ice-cream",
    city: "Santa Cruz",
    region: "NorCal",
    price: "$4.75",
    description: "Three scoops, three toppings, one California classic that's been the same since your grandparents ordered it.",
    vibes: ["fruity"],
    featured: false,
  },
  // ── SCREAMIN' MIMI'S · Sebastopol ────────────────────────────
  {
    id: 20,
    name: "Strawberry Balsamic",
    shop: "Screamin' Mimi's",
    shopSlug: "screamin-mimis",
    city: "Sebastopol",
    region: "NorCal",
    price: "$5.50",
    description: "Sonoma County farm strawberries with aged balsamic reduction. The Sonoma Wine Country version of a perfect summer scoop.",
    vibes: ["fruity"],
    featured: false,
  },
  {
    id: 21,
    name: "Honey Lavender",
    shop: "Screamin' Mimi's",
    shopSlug: "screamin-mimis",
    city: "Sebastopol",
    region: "NorCal",
    price: "$5.50",
    description: "Local Sonoma honey and culinary lavender. A staple of the Northern California farm-stand aesthetic.",
    vibes: ["floral"],
    featured: false,
  },
  // ── THREE TWINS ICE CREAM · Petaluma ─────────────────────────
  {
    id: 22,
    name: "Lemon Cookie",
    shop: "Three Twins Ice Cream",
    shopSlug: "three-twins-ice-cream",
    city: "Petaluma",
    region: "NorCal",
    price: "$5.50",
    description: "Bright Meyer lemon ice cream with house-made cookie crumbles. Certified organic, coastal California in a cup.",
    vibes: ["fruity"],
    featured: false,
  },
  {
    id: 23,
    name: "Banana Fudge Chunk",
    shop: "Three Twins Ice Cream",
    shopSlug: "three-twins-ice-cream",
    city: "Petaluma",
    region: "NorCal",
    price: "$5.50",
    description: "Organic banana ice cream with dark fudge chunks. Retro flavor, modern sourcing.",
    vibes: ["fruity", "chocolate"],
    featured: false,
  },
  // ── STRAUS FAMILY CREAMERY · Marshall ────────────────────────
  {
    id: 24,
    name: "Organic Vanilla Soft Serve",
    shop: "Straus Family Creamery",
    shopSlug: "straus-family-creamery",
    city: "Marshall",
    region: "NorCal",
    price: "$6.00",
    description: "The only soft serve worth driving to West Marin for — made from the same organic herd dairy that supplies Bay Area's finest restaurants.",
    vibes: ["unique"],
    featured: true,
  },
  {
    id: 25,
    name: "Chocolate Soft Serve",
    shop: "Straus Family Creamery",
    shopSlug: "straus-family-creamery",
    city: "Marshall",
    region: "NorCal",
    price: "$6.00",
    description: "Certified organic chocolate, made on-farm with their own herd. Tastes like what chocolate was supposed to taste like.",
    vibes: ["chocolate"],
    featured: false,
  },
  // ── BIG DIPPER CREAMERY · Sacramento ─────────────────────────
  {
    id: 26,
    name: "Honey Bourbon Pecan",
    shop: "Big Dipper Creamery",
    shopSlug: "big-dipper-creamery",
    city: "Sacramento",
    region: "NorCal",
    price: "$5.50",
    description: "Central Valley honey, local bourbon, California pecans. Farm-to-scoop at its most literal and most delicious.",
    vibes: ["nutty"],
    featured: true,
  },
  {
    id: 27,
    name: "Farm Fresh Strawberry",
    shop: "Big Dipper Creamery",
    shopSlug: "big-dipper-creamery",
    city: "Sacramento",
    region: "NorCal",
    price: "$5.00",
    description: "Sourced from Sacramento Delta farms. Seasonal, honest, never artificially flavored.",
    vibes: ["fruity"],
    featured: false,
  },
  {
    id: 28,
    name: "Valley Lavender",
    shop: "Big Dipper Creamery",
    shopSlug: "big-dipper-creamery",
    city: "Sacramento",
    region: "NorCal",
    price: "$5.50",
    description: "California lavender fields, local cream. Agricultural heartland in ice cream form.",
    vibes: ["floral"],
    featured: false,
  },
  // ── TAHOE BLUE COW · South Lake Tahoe ────────────────────────
  {
    id: 29,
    name: "Brown Butter Cookie Dough",
    shop: "Tahoe Blue Cow",
    shopSlug: "tahoe-blue-cow",
    city: "South Lake Tahoe",
    region: "NorCal",
    price: "$6.00",
    description: "Brown butter ice cream with house-made cookie dough chunks. Best eaten at 6,300 feet after a day on the mountain.",
    vibes: ["nutty"],
    featured: true,
  },
  {
    id: 30,
    name: "Sierra Mint Chip",
    shop: "Tahoe Blue Cow",
    shopSlug: "tahoe-blue-cow",
    city: "South Lake Tahoe",
    region: "NorCal",
    price: "$5.75",
    description: "Not the neon green mint chip you grew up with. Fresh mint, dark chocolate, clean and cold like Tahoe air.",
    vibes: ["unique"],
    featured: false,
  },
  // ── MASHTI MALONE'S · Los Angeles ────────────────────────────
  {
    id: 31,
    name: "Rosewater Saffron Pistachio",
    shop: "Mashti Malone's",
    shopSlug: "mashti-malones",
    city: "Los Angeles",
    region: "SoCal",
    price: "$5.50",
    description: "Persian bastani in its purest California form. Saffron threads, rosewater, Bronte pistachios — a flavor profile that exists nowhere else in the world like this.",
    vibes: ["floral", "nutty", "unique"],
    featured: true,
  },
  {
    id: 32,
    name: "Persian Pomegranate",
    shop: "Mashti Malone's",
    shopSlug: "mashti-malones",
    city: "Los Angeles",
    region: "SoCal",
    price: "$5.50",
    description: "Tart pomegranate sorbet with floral notes. LA's Persian community made this iconic.",
    vibes: ["fruity"],
    featured: false,
  },
  {
    id: 33,
    name: "Rose Petal",
    shop: "Mashti Malone's",
    shopSlug: "mashti-malones",
    city: "Los Angeles",
    region: "SoCal",
    price: "$5.50",
    description: "Culinary rose petals, subtle and deeply floral. Either strange or perfect depending on your palate — most people end up in the second camp.",
    vibes: ["floral"],
    featured: false,
  },
  // ── SALT & STRAW · Los Angeles ───────────────────────────────
  {
    id: 34,
    name: "Honey Lavender",
    shop: "Salt & Straw",
    shopSlug: "salt-and-straw",
    city: "Los Angeles",
    region: "SoCal",
    price: "$7.00",
    description: "The scoop that put Salt & Straw on the national map. Local honey, culinary lavender — simple idea, perfect execution.",
    vibes: ["floral"],
    featured: true,
  },
  {
    id: 35,
    name: "Pear & Gorgonzola",
    shop: "Salt & Straw",
    shopSlug: "salt-and-straw",
    city: "Los Angeles",
    region: "SoCal",
    price: "$7.50",
    description: "Controversial, divisive, and genuinely great. Blue cheese in ice cream should not work and yet it absolutely does.",
    vibes: ["savory-sweet", "unique"],
    featured: false,
  },
  {
    id: 36,
    name: "Sea Salt Caramel Ribbon",
    shop: "Salt & Straw",
    shopSlug: "salt-and-straw",
    city: "Los Angeles",
    region: "SoCal",
    price: "$7.00",
    description: "Oregon sea salt and caramel ribboned through a cream base. The accessible entry point to Salt & Straw's broader catalog.",
    vibes: ["nutty"],
    featured: false,
  },
  // ── SWEET ROSE CREAMERY · Santa Monica ───────────────────────
  {
    id: 37,
    name: "Salted Caramel",
    shop: "Sweet Rose Creamery",
    shopSlug: "sweet-rose-creamery",
    city: "Santa Monica",
    region: "SoCal",
    price: "$6.50",
    description: "Small-batch caramel with Maldon sea salt flakes. The Santa Monica version of the Bay Area standard — and it holds its own.",
    vibes: ["nutty"],
    featured: false,
  },
  {
    id: 38,
    name: "Brown Butter Almond Brittle",
    shop: "Sweet Rose Creamery",
    shopSlug: "sweet-rose-creamery",
    city: "Santa Monica",
    region: "SoCal",
    price: "$6.50",
    description: "Toasted brown butter ice cream with hand-made almond brittle shards. The best scoop on the Santa Monica menu.",
    vibes: ["nutty"],
    featured: true,
  },
  {
    id: 39,
    name: "Strawberry Balsamic Vinegar",
    shop: "Sweet Rose Creamery",
    shopSlug: "sweet-rose-creamery",
    city: "Santa Monica",
    region: "SoCal",
    price: "$6.50",
    description: "California strawberries with aged balsamic swirl. Coastal California's answer to classic Italian gelato traditions.",
    vibes: ["fruity"],
    featured: false,
  },
  // ── CARMELA ICE CREAM · Pasadena ─────────────────────────────
  {
    id: 40,
    name: "Brown Sugar & Cinnamon",
    shop: "Carmela Ice Cream",
    shopSlug: "carmela-ice-cream",
    city: "Pasadena",
    region: "SoCal",
    price: "$6.00",
    description: "The Pasadena neighborhood scoop. Warm spice, deep sugar, and cream that tastes like it came from a family recipe.",
    vibes: ["nutty"],
    featured: false,
  },
  {
    id: 41,
    name: "Rose",
    shop: "Carmela Ice Cream",
    shopSlug: "carmela-ice-cream",
    city: "Pasadena",
    region: "SoCal",
    price: "$6.00",
    description: "Culinary rose extract in premium cream. Delicate, floral, and surprisingly addictive.",
    vibes: ["floral"],
    featured: false,
  },
  {
    id: 42,
    name: "Earl Grey Tea",
    shop: "Carmela Ice Cream",
    shopSlug: "carmela-ice-cream",
    city: "Pasadena",
    region: "SoCal",
    price: "$6.00",
    description: "Bergamot-forward Earl Grey steeped into a rich cream base. The tea-lover's ice cream, done correctly.",
    vibes: ["unique"],
    featured: true,
  },
  // ── FOSSELMAN'S ICE CREAM · Alhambra ─────────────────────────
  {
    id: 43,
    name: "Ube Purple Yam",
    shop: "Fosselman's Ice Cream",
    shopSlug: "fosselmans",
    city: "Alhambra",
    region: "SoCal",
    price: "$5.00",
    description: "Filipino purple yam in a century-old parlor. A flavor that reflects the real Los Angeles — available here long before ube went mainstream.",
    vibes: ["unique"],
    featured: true,
  },
  {
    id: 44,
    name: "Rocky Road",
    shop: "Fosselman's Ice Cream",
    shopSlug: "fosselmans",
    city: "Alhambra",
    region: "SoCal",
    price: "$5.00",
    description: "Chocolate, marshmallow, almonds — the California original since 1919. Fosselman's Rocky Road is old-school in the best possible way.",
    vibes: ["chocolate", "nutty"],
    featured: false,
  },
  {
    id: 45,
    name: "Pistachio",
    shop: "Fosselman's Ice Cream",
    shopSlug: "fosselmans",
    city: "Alhambra",
    region: "SoCal",
    price: "$5.00",
    description: "A century-old family recipe. Real pistachio, not the artificially green kind. The LA San Gabriel Valley standard.",
    vibes: ["nutty"],
    featured: false,
  },
  // ── SCOOPS · Los Angeles ──────────────────────────────────────
  {
    id: 46,
    name: "Brown Bread",
    shop: "Scoops",
    shopSlug: "scoops",
    city: "Los Angeles",
    region: "SoCal",
    price: "$5.00",
    description: "Ice cream made with brown bread crumbs and stout. An East Hollywood institution that operates by its own logic and gets away with it.",
    vibes: ["unique"],
    featured: true,
  },
  {
    id: 47,
    name: "Brown Butter Stracciatella",
    shop: "Scoops",
    shopSlug: "scoops",
    city: "Los Angeles",
    region: "SoCal",
    price: "$5.00",
    description: "Brown butter ice cream with fine dark chocolate ribbons. Scoops at its most elegant.",
    vibes: ["nutty", "chocolate"],
    featured: false,
  },
  {
    id: 48,
    name: "Toasted Coconut",
    shop: "Scoops",
    shopSlug: "scoops",
    city: "Los Angeles",
    region: "SoCal",
    price: "$5.00",
    description: "Slow-toasted coconut folded into a dairy-free base. The best dairy-free scoop you'll find in East Hollywood.",
    vibes: ["dairy-free", "unique"],
    featured: false,
  },
  // ── COOLHAUS · Los Angeles ────────────────────────────────────
  {
    id: 49,
    name: "Dirty Mint Chip",
    shop: "Coolhaus",
    shopSlug: "coolhaus",
    city: "Los Angeles",
    region: "SoCal",
    price: "$6.00",
    description: "Fresh mint leaf (not extract), dark chocolate chunks. The mint chip for people who think they don't like mint chip.",
    vibes: ["chocolate"],
    featured: false,
  },
  {
    id: 50,
    name: "Fried Chicken & Waffles",
    shop: "Coolhaus",
    shopSlug: "coolhaus",
    city: "Los Angeles",
    region: "SoCal",
    price: "$6.50",
    description: "Maple syrup ice cream, cornbread waffle pieces, cayenne caramel. Only in Los Angeles. Only Coolhaus.",
    vibes: ["savory-sweet", "unique"],
    featured: true,
  },
  // ── CREAMISTRY · Irvine ───────────────────────────────────────
  {
    id: 51,
    name: "Nitrogen-Churned Vanilla",
    shop: "Creamistry",
    shopSlug: "creamistry",
    city: "Irvine",
    region: "SoCal",
    price: "$7.00",
    description: "Made to order in liquid nitrogen. The creamiest, freshest vanilla in Orange County — and there's nowhere else to get the experience quite like this.",
    vibes: ["unique"],
    featured: false,
  },
  {
    id: 52,
    name: "Matcha Green Tea",
    shop: "Creamistry",
    shopSlug: "creamistry",
    city: "Irvine",
    region: "SoCal",
    price: "$7.00",
    description: "Premium Japanese matcha, nitrogen-spun on the spot. The Green Tea scoop for serious matcha people.",
    vibes: ["unique"],
    featured: false,
  },
  // ── NAIA GELATO · Los Angeles ─────────────────────────────────
  {
    id: 53,
    name: "Passion Fruit",
    shop: "Naia Gelato",
    shopSlug: "naia-gelato",
    city: "Los Angeles",
    region: "SoCal",
    price: "$5.50",
    description: "Plant-based gelato that doesn't taste like a compromise. Bright, tropical, genuinely tart — and fully dairy-free.",
    vibes: ["fruity", "dairy-free"],
    featured: false,
  },
  {
    id: 54,
    name: "Coconut Mylk",
    shop: "Naia Gelato",
    shopSlug: "naia-gelato",
    city: "Los Angeles",
    region: "SoCal",
    price: "$5.50",
    description: "Creamy, rich, and entirely plant-based. The best dairy-free gelato in California for people who want real flavor.",
    vibes: ["dairy-free", "unique"],
    featured: false,
  },
  // ── LORD'S ICE CREAM · Los Angeles ───────────────────────────
  {
    id: 55,
    name: "Classic Vanilla",
    shop: "Lord's Ice Cream",
    shopSlug: "lords-ice-cream",
    city: "Los Angeles",
    region: "SoCal",
    price: "$5.00",
    description: "Old-school neighborhood creamery vanilla. No trends, no gimmicks — just a scoop that's been making locals happy for decades.",
    vibes: ["unique"],
    featured: false,
  },
  {
    id: 56,
    name: "Chocolate Chip",
    shop: "Lord's Ice Cream",
    shopSlug: "lords-ice-cream",
    city: "Los Angeles",
    region: "SoCal",
    price: "$5.00",
    description: "Classic chocolate chip from a classic LA neighborhood shop. The scoop that reminds you why the simple ones endure.",
    vibes: ["chocolate"],
    featured: false,
  },
  // ── McCONNELL'S · Santa Barbara ──────────────────────────────
  {
    id: 57,
    name: "Eureka Lemon & Marionberries",
    shop: "McConnell's Fine Ice Creams",
    shopSlug: "mcconnells-fine-ice-creams",
    city: "Santa Barbara",
    region: "SoCal",
    price: "$6.50",
    description: "Channel Islands dairy, Central Coast Eureka lemons, Oregon marionberries. This is what ice cream tastes like when the supply chain is 100 miles long.",
    vibes: ["fruity"],
    featured: true,
  },
  {
    id: 58,
    name: "Turkish Coffee",
    shop: "McConnell's Fine Ice Creams",
    shopSlug: "mcconnells-fine-ice-creams",
    city: "Santa Barbara",
    region: "SoCal",
    price: "$6.50",
    description: "Cardamom-laced Turkish coffee steeped into their Channel Islands cream base. Unexpectedly the best coffee ice cream in California.",
    vibes: ["unique"],
    featured: false,
  },
  {
    id: 59,
    name: "Double Peanut Butter Chip",
    shop: "McConnell's Fine Ice Creams",
    shopSlug: "mcconnells-fine-ice-creams",
    city: "Santa Barbara",
    region: "SoCal",
    price: "$6.50",
    description: "Peanut butter ice cream, peanut butter swirl, dark chocolate chips. The indulgent McConnell's scoop for people who don't want to think too hard.",
    vibes: ["nutty", "chocolate"],
    featured: false,
  },
  // ── HAMMOND'S GOURMET ICE CREAM · San Diego ──────────────────
  {
    id: 60,
    name: "Sea Salt Caramel",
    shop: "Hammond's Gourmet Ice Cream",
    shopSlug: "hammonds-gourmet",
    city: "San Diego",
    region: "SoCal",
    price: "$5.50",
    description: "San Diego's answer to the salted caramel obsession — local sea salt, slow-cooked caramel, and that coastal air freshness.",
    vibes: ["nutty"],
    featured: false,
  },
  {
    id: 61,
    name: "Lavender Honey",
    shop: "Hammond's Gourmet Ice Cream",
    shopSlug: "hammonds-gourmet",
    city: "San Diego",
    region: "SoCal",
    price: "$5.50",
    description: "San Diego County lavender farms meet local honey. Floral without being overpowering — the perfect summer coastal scoop.",
    vibes: ["floral"],
    featured: false,
  },
  // ── MARIPOSA ICE CREAM · San Diego ───────────────────────────
  {
    id: 62,
    name: "Horchata",
    shop: "Mariposa Ice Cream",
    shopSlug: "mariposa-ice-cream",
    city: "San Diego",
    region: "SoCal",
    price: "$5.00",
    description: "The cinnamon rice milk drink of Mexican street culture, churned into ice cream. San Diego's most iconic scoop.",
    vibes: ["unique", "savory-sweet"],
    featured: true,
  },
  {
    id: 63,
    name: "Queso con Guayaba",
    shop: "Mariposa Ice Cream",
    shopSlug: "mariposa-ice-cream",
    city: "San Diego",
    region: "SoCal",
    price: "$5.00",
    description: "Cream cheese ice cream ribboned with guava paste. A traditional Mexican flavor combination that works perfectly frozen.",
    vibes: ["fruity", "savory-sweet", "unique"],
    featured: false,
  },
  {
    id: 64,
    name: "Mexican Chocolate Mole",
    shop: "Mariposa Ice Cream",
    shopSlug: "mariposa-ice-cream",
    city: "San Diego",
    region: "SoCal",
    price: "$5.00",
    description: "Authentic mole spices — chili, cinnamon, dark chocolate — in a cream base. You'll understand why this belongs on the list.",
    vibes: ["chocolate", "savory-sweet"],
    featured: false,
  },
  // ── GELATO PARADISO · Palm Springs ───────────────────────────
  {
    id: 65,
    name: "Sicilian Pistachio",
    shop: "Gelato Paradiso",
    shopSlug: "gelato-paradiso",
    city: "Palm Springs",
    region: "SoCal",
    price: "$6.50",
    description: "Bronte pistachio paste imported from Sicily, churned into a dense gelato. In the middle of the California desert. Worth every mile.",
    vibes: ["nutty"],
    featured: true,
  },
  {
    id: 66,
    name: "Stracciatella",
    shop: "Gelato Paradiso",
    shopSlug: "gelato-paradiso",
    city: "Palm Springs",
    region: "SoCal",
    price: "$6.00",
    description: "Fior di latte gelato with fine dark chocolate drizzled in by hand. The Italian standard, done correctly in the desert.",
    vibes: ["chocolate"],
    featured: false,
  },
  {
    id: 67,
    name: "Limoncello Sorbetto",
    shop: "Gelato Paradiso",
    shopSlug: "gelato-paradiso",
    city: "Palm Springs",
    region: "SoCal",
    price: "$6.00",
    description: "Dairy-free, tart, and crushingly refreshing at 110°F. The only reasonable response to a Palm Springs summer.",
    vibes: ["fruity", "dairy-free"],
    featured: false,
  },
  // ── THRIFTY ICE CREAM · Statewide ────────────────────────────
  {
    id: 68,
    name: "Chocolate Malted Crunch",
    shop: "Thrifty Ice Cream",
    shopSlug: "thrifty-ice-cream",
    city: "Los Angeles",
    region: "SoCal",
    price: "$2.50",
    description: "The $2.50 scoop sold at Rite Aid stores in that iconic cylinder shape since 1940. Chocolate ice cream with malt crunch pieces. California's most democratic iconic flavor.",
    vibes: ["chocolate"],
    featured: true,
  },
  {
    id: 69,
    name: "Rainbow Sherbet",
    shop: "Thrifty Ice Cream",
    shopSlug: "thrifty-ice-cream",
    city: "Los Angeles",
    region: "SoCal",
    price: "$2.50",
    description: "Three fruit sherbet flavors in one cylindrical scoop. Every California kid grew up on this. Some things don't need to change.",
    vibes: ["fruity"],
    featured: false,
  },
]

export function getFeaturedFlavors(): IceCreamFlavor[] {
  return FLAVORS.filter((f) => f.featured)
}

export function getFlavorsByRegion(region: FlavorRegion): IceCreamFlavor[] {
  return FLAVORS.filter((f) => f.region === region)
}

export function getFlavorsByShop(shopSlug: string): IceCreamFlavor[] {
  return FLAVORS.filter((f) => f.shopSlug === shopSlug)
}

export function getFlavorsByVibe(vibe: string): IceCreamFlavor[] {
  return FLAVORS.filter((f) => f.vibes.includes(vibe))
}
